AWSTemplateFormatVersion: '2010-09-09'
Description: "Pipeline stack (CodePipeline + CodeBuild) for SAM app (message-router). Deploy separately from the application stack. Uses GitHub OAuth token stored in Secrets Manager."

Parameters:
  GitHubRepoOwner:
    Type: String
    Description: "GitHub owner (user or org) of the repo"
  
  GitHubRepoName:
    Type: String
    Default: message-router
    Description: "Repository name (message-router)"
  
  GitHubBranch:
    Type: String
    Default: main
    Description: "Branch the pipeline will watch"
  
  GitHubPATSecretName:
    Type: String
    Default: github/message-router/pat
    Description: "Name of the secret in AWS Secrets Manager that contains the GitHub PAT (JSON with key 'token')"
  
  PipelineName:
    Type: String
    Default: message-router-pipeline
  
  DeployStackName:
    Type: String
    Default: message-router-prod

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PipelineName}-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # NOTE: AdministratorAccess is broad — tighten in production to minimum privileges required.
        - arn:aws:iam::aws:policy/AdministratorAccess

  SAMBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${PipelineName}-Build"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref PipelineArtifactBucket
          - Name: AWS_DEFAULT_REGION
            Value: !Ref "AWS::Region"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                python: 3.12
              commands:
                - python -V
                - pip install --upgrade pip
                - pip install aws-sam-cli
                - sam --version || true
            build:
              commands:
                - echo "Running sam build..."
                - sam build
                - echo "Packaging into S3 bucket $ARTIFACT_BUCKET..."
                - sam package --template-file .aws-sam/build/template.yaml --s3-bucket "$ARTIFACT_BUCKET" --output-template-file packaged-template.yaml

          artifacts:
            files:
              - packaged-template.yaml


  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PipelineName}-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodePipelineS3AndCodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${PipelineArtifactBucket.Arn}"
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CFNExecutionRole.Arn

        - PolicyName: CodePipelineSecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GitHubPATSecretName}*"
        
        - PolicyName: CodePipelineCloudFormationAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"
        
        - PolicyName: CodePipelineCloudFormationCreateAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/*"
        
        - PolicyName: CodePipelineCloudFormationDescribeEvents
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:ListStackResources
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"


  CFNExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PipelineName}-CFNExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess


  # IAM role for tests
  SAMTestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SAMTestPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${PipelineArtifactBucket.Arn}"
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}-test-*/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/*"
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - s3:*
                  - sns:*
                  - sqs:*
                  - lambda:*
                  - events:*
                  - cloudwatch:*
                  - logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CFNExecutionRole.Arn

  # CodeBuild project for tests
  SAMTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${PipelineName}-Test"
      ServiceRole: !GetAtt SAMTestRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref PipelineArtifactBucket
          - Name: DEPLOY_STACK_NAME
            Value: !Ref DeployStackName
          - Name: CFN_EXECUTION_ROLE_ARN
            Value: !GetAtt CFNExecutionRole.Arn
          - Name: RUN_E2E
            Value: "false"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                python: 3.12
              commands:
                - python -V
                - pip install --upgrade pip
                - |
                  # establecer PYTHONPATH (ruta absoluta)
                  export PYTHONPATH="$(pwd)/backend/src:$(pwd)/backend:$PYTHONPATH"
                - echo "CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION"
                - echo "Printing a short tree of repo (top-level):"
                - ls -la
                - echo "Printing backend tree:"
                - ls -la backend || true
                - echo "Printing tests folder:"
                - ls -la backend/tests || true
                - echo "Show test file head (first 80 lines):"
                - sed -n '1,80p' backend/tests/unit/test_handler.py || true
                - if [ -f backend/tests/requirements.txt ]; then pip install -r backend/tests/requirements.txt; else echo "backend/tests/requirements.txt not found -> installing minimal test deps" && pip install pytest pytest-mock || exit 1; fi
            build:
              commands:
                - echo "PYTHONPATH=$PYTHONPATH"
                - echo "Running unit tests..."
                - pytest -q backend/tests/unit




  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub '{{resolve:secretsmanager:${GitHubPATSecretName}:SecretString:token}}'
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: SAMBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref SAMBuildProject

        - Name: Test
          Actions:
            - Name: RunTests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: !Ref SAMTestProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: CFN_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref DeployStackName
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: BuildArtifact::packaged-template.yaml
                RoleArn: !GetAtt CFNExecutionRole.Arn


Outputs:
  PipelineName:
    Description: "CodePipeline name"
    Value: !Ref PipelineName
  PipelineArtifactBucket:
    Description: "S3 bucket for pipeline artifacts"
    Value: !Ref PipelineArtifactBucket
  CodeBuildProjectName:
    Description: "CodeBuild project used by pipeline"
    Value: !Ref SAMBuildProject
  SecretName:
    Description: "Secrets Manager secret name expected (contains GitHub PAT)"
    Value: !Ref GitHubPATSecretName
