AWSTemplateFormatVersion: '2010-09-09'
Description: "Pipeline stack (CodePipeline + CodeBuild) for SAM app (message-router). Deploy separately from the application stack. Uses GitHub OAuth token stored in Secrets Manager."

Parameters:
  GitHubRepoOwner:
    Type: String
    Description: "GitHub owner (user or org) of the repo"
  
  GitHubRepoName:
    Type: String
    Default: message-router
    Description: "Repository name (message-router)"
  
  GitHubBranch:
    Type: String
    Default: stellios #main
    Description: "Branch the pipeline will watch"
  
  GitHubPATSecretName:
    Type: String
    Default: github/message-router/pat
    Description: "Name of the secret in AWS Secrets Manager that contains the GitHub PAT (JSON with key 'token')"
  
  PipelineName:
    Type: String
    Default: message-router-pipeline
  
  DeployStackName:
    Type: String
    Default: message-router-prod

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # NOTE: AdministratorAccess is broad — tighten in production to minimum privileges required.
        - arn:aws:iam::aws:policy/AdministratorAccess

  SAMBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${PipelineName}-Build"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref PipelineArtifactBucket
          - Name: AWS_DEFAULT_REGION
            Value: !Ref "AWS::Region"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                python: 3.12
              commands:
                - python -V
                - pip install --upgrade pip
                - pip install aws-sam-cli
                - sam --version || true
            build:
              commands:
                - echo "Running sam build..."
                - sam build
                - echo "Packaging into S3 bucket $ARTIFACT_BUCKET..."
                - sam package --template-file .aws-sam/build/template.yaml --s3-bucket "$ARTIFACT_BUCKET" --output-template-file packaged-template.yaml

          artifacts:
            files:
              - packaged-template.yaml


  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodePipelineS3AndCodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${PipelineArtifactBucket.Arn}"
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CFNExecutionRole.Arn

        - PolicyName: CodePipelineSecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GitHubPATSecretName}*"
        
        - PolicyName: CodePipelineCloudFormationAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"
        
        - PolicyName: CodePipelineCloudFormationCreateAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/*"
        
        - PolicyName: CodePipelineCloudFormationDescribeEvents
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:ListStackResources
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}/*"


  CFNExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess


  # Role usado por CodeBuild para el Test stage
  SAMTestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SAMTestPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # 1) Permisos S3 para artefactos
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${PipelineArtifactBucket.Arn}"
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
              # 2) Permisos CloudFormation para stacks de test (crear/actualizar/borrar/describe)
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${DeployStackName}-test-*/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/*"
              # 3) Permisos para crear recursos comunes durante tests (Dynamo, S3, SNS, Lambda, IAM if needed)
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - s3:*
                  - sns:*
                  - sqs:*
                  - lambda:*
                  - events:*
                  - cloudwatch:*
                  - logs:*
                Resource: "*"
              # 4) Permitir pasar el CFN execution role a CloudFormation (si usas --role-arn)
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CFNExecutionRole.Arn


  SAMTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${PipelineName}-Test"
      ServiceRole: !GetAtt SAMTestRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref PipelineArtifactBucket
          - Name: AWS_DEFAULT_REGION
            Value: !Ref "AWS::Region"
          - Name: DEPLOY_STACK_NAME
            Value: !Ref DeployStackName
          - Name: CFN_EXECUTION_ROLE_ARN
            Value: !GetAtt CFNExecutionRole.Arn
          # control: si queremos correr E2E o no
          - Name: RUN_E2E
            Value: "false"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                python: 3.12
              commands:
                - python -V
                - pip install --upgrade pip
                - pip install -r backend/requirements-test.txt || true
                - pip install aws-sam-cli || true
            build:
              commands:
                - echo "Running unit tests..."
                - pytest -q backend/tests/unit || exit 1
                - echo "Running integration tests..."
                - pytest -q backend/tests/integration || exit 1
                - |
                  if [ "$RUN_E2E" = "true" ]; then
                    echo "RUN_E2E=true -> packaging and deploying test stack..."
                    export TEST_STACK_NAME="${DEPLOY_STACK_NAME}-test-${CODEBUILD_BUILD_ID}"
                    sam package --template-file .aws-sam/build/template.yaml --s3-bucket "$ARTIFACT_BUCKET" --output-template-file packaged-test-template.yaml
                    aws cloudformation deploy \
                      --template-file packaged-test-template.yaml \
                      --stack-name "$TEST_STACK_NAME" \
                      --capabilities CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND \
                      --role-arn "$CFN_EXECUTION_ROLE_ARN"
                    # obtener endpoint del stack temporal (si existe Output ApiUrl)
                    API_URL=$(aws cloudformation describe-stacks --stack-name "$TEST_STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
                    echo "API_URL: $API_URL"
                    # ejecutar pruebas e2e (ejemplo)
                    pytest -q backend/tests/e2e --api-url "$API_URL" || TEST_FAILED=1
                    echo "Cleaning up test stack $TEST_STACK_NAME"
                    aws cloudformation delete-stack --stack-name "$TEST_STACK_NAME"
                    aws cloudformation wait stack-delete-complete --stack-name "$TEST_STACK_NAME"
                    if [ -n "$TEST_FAILED" ]; then
                      echo "E2E tests failed"
                      exit 1
                    fi
                  else
                    echo "RUN_E2E != true -> skipping E2E stage"
                  fi
          reports: {}


  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub '{{resolve:secretsmanager:${GitHubPATSecretName}:SecretString:token}}'
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: SAMBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref SAMBuildProject

        - Name: Test
          Actions:
            - Name: RunTests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref SAMTestProject
              RunOrder: 1

        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: "Revisar resultados de tests antes de desplegar a prod"
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: CFN_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref DeployStackName
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: BuildArtifact::packaged-template.yaml
                RoleArn: !GetAtt CFNExecutionRole.Arn


Outputs:
  PipelineName:
    Description: "CodePipeline name"
    Value: !Ref PipelineName
  PipelineArtifactBucket:
    Description: "S3 bucket for pipeline artifacts"
    Value: !Ref PipelineArtifactBucket
  CodeBuildProjectName:
    Description: "CodeBuild project used by pipeline"
    Value: !Ref SAMBuildProject
  SecretName:
    Description: "Secrets Manager secret name expected (contains GitHub PAT)"
    Value: !Ref GitHubPATSecretName
