AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM app - SNS -> Lambda -> DynamoDB

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:

  # --- SQS Queue ---
  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyMessageQueue

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: message_router_queue/
      Handler: app.lambda_handler
      Environment:
        Variables:
          QUEUE_URL: !Ref MessageQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MessageQueue.QueueName
      Events:
        ApiPost:
          Type: Api
          Properties:
            Path: /send
            Method: post

  # --- DynamoDB Table ---
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MessagesTable
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # --- SNS Topic ---
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MyTargetTopic

  # --- Lambda que inserta en DynamoDB ---
  DynamoLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_dynamo/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          TABLE_NAME: !Ref MessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable

  # --- Permisos para que SNS invoque al Lambda ---
  PermissionForSNSInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DynamoLambda
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref MySNSTopic

  # --- Suscripción SNS a Lambda ---
  DynamoLambdaSubscription:
    Type: AWS::SNS::Subscription
    DependsOn: PermissionForSNSInvokeLambda
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt DynamoLambda.Arn
      TopicArn: !Ref MySNSTopic

  
    # --- Lambda Dispatcher: SQS -> EventBridge ---
  LambdaDispatcher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_dispatcher/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MessageQueue.QueueName
        - Statement:
            Effect: Allow
            Action:
              - events:PutEvents
            Resource: "*"
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn
            BatchSize: 1

  # === EventBridge Rule 1 -> SNS ===
  EventRuleToSNS:
    Type: AWS::Events::Rule
    Properties:
      Name: SendToSNSRule
      Description: "Regla de EventBridge que publica en SNS"
      EventPattern:
        source:
          - "MyApp"
          - "my.custom.source"
        detail-type:
          - "PlainText"
          - "MyEvent"
      Targets:
        - Arn: !Ref MySNSTopic
          Id: "SnsTarget"

  # Permiso para que EventBridge publique en SNS
  EventBridgeToSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MySNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEventBridgeToPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref MySNSTopic

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send"
  SNSTopicArn:
    Description: "ARN del tópico SNS"
    Value: !Ref MySNSTopic
  DynamoDBTableName:
    Description: "SnsMessage"
    Value: !Ref MessagesTable