AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM App: SNS -> Lambda -> DynamoDB -> Lambda -> S3

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Layers: 
     - !Ref CommonDependenciesLayer
  Api:
    TracingEnabled: true   #  ACTIVAR X-RAY EN API GATEWAY

Resources:
  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.12


  # --- [Lambda] Message router queue: API Gateway -> SQS ---

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: message_router_queue/
      Handler: app.lambda_handler
      Tracing: Active

      Environment:
        Variables:
          QUEUE_URL: !Ref MessageQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MessageQueue.QueueName
        - AWSXRayDaemonWriteAccess

      Events:
        ApiPost:
          Type: Api
          Properties:
            Path: /send
            Method: post

  # --- SQS Queue ---
  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyMessageQueue

  # --- Lambda Dispatcher: SQS -> EventBridge ---
  LambdaDispatcher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_dispatcher/
      Handler: app.lambda_handler
      Tracing: Active
      Runtime: python3.12
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MessageQueue.QueueName
        - Statement:
            Effect: Allow
            Action:
              - events:PutEvents
            Resource: "*"
        - AWSXRayDaemonWriteAccess   #  Permiso X-Ray
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn
            BatchSize: 1

  # --- EventBridge Rule 1 -> SNS ---
  EventRuleToSNS:
    Type: AWS::Events::Rule
    Properties:
      Name: SendToSNSRule
      Description: "Regla de EventBridge que publica en SNS"
      EventPattern:
        source:
          - "MyApp"
          - "my.custom.source"
        detail-type:
          - "PlainText"
          - "MyEvent"
      Targets:
        - Arn: !Ref MySNSTopic
          Id: "SnsTarget"

  # Policy that allows EventBridge to publish in SNS
  EventBridgeToSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MySNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEventBridgeToPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref MySNSTopic

  # --- SNS Topic ---
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MyTargetTopic

  # Permissions for SNS to invoke Lambda
  PermissionForSNSInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DynamoLambda
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref MySNSTopic

  # SNS subscription to Lambda
  DynamoLambdaSubscription:
    Type: AWS::SNS::Subscription
    DependsOn: PermissionForSNSInvokeLambda
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt DynamoLambda.Arn
      TopicArn: !Ref MySNSTopic

  # --- Lambda Dynamo: SNS -> DynamoDB ---
  DynamoLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_dynamo/
      Handler: app.lambda_handler
      Tracing: Active
      Runtime: python3.12
      Environment:
        Variables:
          TABLE_NAME: !Ref MessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - AWSXRayDaemonWriteAccess   #  Permiso X-Ray

  # --- DynamoDB ---
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MessagesTable
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # --- Lambda DDB to S3: DynamoDB -> S3 ---
  DdbToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-DdbToS3Handler'
      Handler: app.lambda_handler
      Tracing: Active
      CodeUri: lambda_ddb_to_s3/   
      Timeout: 30      
      Environment:
        Variables:
          S3_BUCKET: !Ref TargetBucket
      Events:
        DdbStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MessagesTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST 
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MessagesTable
        - S3WritePolicy:
            BucketName: !Ref TargetBucket
        - AWSXRayDaemonWriteAccess   #  Permiso X-Ray

  # --- S3 Bucket ---
  TargetBucket:
    Type: AWS::S3::Bucket



Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send"
  SNSTopicArn:
    Description: "SNS Topic ARN"
    Value: !Ref MySNSTopic
  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref MessagesTable
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref TargetBucket




